### ISSUE TITLE
clean up DeleteButton and AddVideoButton

### ISSUE THREAD

**Issue by filkovsp** [nazary001/Full-Stack-Project-Assessment#5]
example for DeleteButton: 
```js
    <button href="#"  onClick={deleteVideo} className='delete_button'>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      Delete
  </button>
```
what are those `<span/>` for?

**Comment by nazary001** [comment]
These <spans> were used to decorate the buttons in my css, but later I replaced these buttons with simpler ones from the library.

**Comment by nazary001** [comment]
These <spans> were used to decorate the buttons in my css, but later I replaced these buttons with simpler ones from the library.

**Comment by nazary001** [comment]
These spans were used to decorate the buttons in my css, but later I replaced these buttons with simpler ones from the library.
